version: '3.8'
services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: user_subscriptions
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5433:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: